# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

ProblemCategory.create(problem:'Kiosk 查詢平台')
ProblemCategory.create(problem:'非靠卡電腦')
ProblemCategory.create(problem:'一般靠卡電腦')
ProblemCategory.create(problem:'預約靠卡電腦')
ProblemCategory.create(problem:'多媒體設備')

Machine.create(place:'總圖', floor:1, group:'查詢平台', machine_name:'Kiosk_1F')
Machine.create(place:'總圖', floor:2, group:'查詢平台', machine_name:'Kiosk_2F')
Machine.create(place:'總圖', floor:3, group:'查詢平台', machine_name:'Kiosk_3F')
Machine.create(place:'總圖', floor:4, group:'查詢平台', machine_name:'Kiosk_4F')
Machine.create(place:'總圖', floor:5, group:'查詢平台', machine_name:'Kiosk_5F')
Machine.create(place:'總圖', floor:6, group:'查詢平台', machine_name:'Kiosk_6F')
Machine.create(place:'總圖', floor:4, group:'夜讀區查詢平台', machine_name:'Kiosk_夜1')
Machine.create(place:'總圖', floor:4, group:'夜讀區查詢平台', machine_name:'Kiosk_夜2')
Machine.create(place:'總圖', floor:4, group:'夜讀區查詢平台', machine_name:'Kiosk_夜3')

Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F101')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F102')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F103')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F104')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F105')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F106')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F107')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F108')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F109')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F110')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F111')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F112')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F113')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F114')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F115')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F116')
Machine.create(place:'總圖', floor:1, group:'資訊島', machine_name:'F117')
Machine.create(place:'總圖', floor:1, group:'知識集', machine_name:'書展區')

Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F201')
Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F202')
Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F203')
Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F204')
Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F205')
Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F206')
Machine.create(place:'總圖', floor:2, group:'資訊島', machine_name:'F207')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'留念清華')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'校園景觀')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'校史大事記')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'入口意象')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'特展區')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'查詢平台(左)')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'查詢平台(右)')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'電子書')
Machine.create(place:'總圖', floor:2, group:'多媒體', machine_name:'校歌、情歌撥放')

Machine.create(place:'總圖', floor:3, group:'資訊島', machine_name:'F301')
Machine.create(place:'總圖', floor:3, group:'資訊島', machine_name:'F302')
Machine.create(place:'總圖', floor:3, group:'資訊島', machine_name:'F303')
Machine.create(place:'總圖', floor:3, group:'資訊島', machine_name:'F304')
Machine.create(place:'總圖', floor:3, group:'資訊島', machine_name:'F305')

Machine.create(place:'總圖', floor:4, group:'資訊島', machine_name:'F401')
Machine.create(place:'總圖', floor:4, group:'資訊島', machine_name:'F402')
Machine.create(place:'總圖', floor:4, group:'資訊島', machine_name:'F403')
Machine.create(place:'總圖', floor:4, group:'資訊島', machine_name:'F404')
Machine.create(place:'總圖', floor:4, group:'資訊島', machine_name:'F405')
Machine.create(place:'總圖', floor:4, group:'書架區', machine_name:'F406')
Machine.create(place:'總圖', floor:4, group:'書架區', machine_name:'F407')
Machine.create(place:'總圖', floor:4, group:'書架區', machine_name:'F408')
Machine.create(place:'總圖', floor:4, group:'經典書房', machine_name:'F409')
Machine.create(place:'總圖', floor:4, group:'經典書房', machine_name:'F410')

Machine.create(place:'總圖', floor:5, group:'資訊島', machine_name:'F501')
Machine.create(place:'總圖', floor:5, group:'資訊島', machine_name:'F502')
Machine.create(place:'總圖', floor:5, group:'資訊島', machine_name:'F503')
Machine.create(place:'總圖', floor:5, group:'資訊島', machine_name:'F504')
Machine.create(place:'總圖', floor:5, group:'資訊島', machine_name:'F505')
Machine.create(place:'總圖', floor:5, group:'書架區', machine_name:'F506')
Machine.create(place:'總圖', floor:5, group:'書架區', machine_name:'F507')
Machine.create(place:'總圖', floor:5, group:'書架區', machine_name:'F508')
Machine.create(place:'總圖', floor:5, group:'書架區', machine_name:'F509')

Machine.create(place:'總圖', floor:6, group:'資訊島', machine_name:'F601')
Machine.create(place:'總圖', floor:6, group:'資訊島', machine_name:'F602')
Machine.create(place:'總圖', floor:6, group:'資訊島', machine_name:'F603')
Machine.create(place:'總圖', floor:6, group:'資訊島', machine_name:'F604')
Machine.create(place:'總圖', floor:6, group:'資訊島', machine_name:'F605')
Machine.create(place:'總圖', floor:6, group:'書架區', machine_name:'F606')
Machine.create(place:'總圖', floor:6, group:'書架區', machine_name:'F607')
Machine.create(place:'總圖', floor:6, group:'書架區', machine_name:'F608')
Machine.create(place:'總圖', floor:6, group:'書架區', machine_name:'F609')

Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C201')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C202')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C203')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C204')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C205')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C206')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C207')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C208')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C209')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C210')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C211')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C212')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C213')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C214')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C215')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C216')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C217')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C218')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C219')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C220')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C221')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C222')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C223')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C224')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C225')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C226')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C227')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C228')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C229')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C230')
Machine.create(place:'總圖', floor:2, group:'學習共享區', machine_name:'C231')

Machine.create(place:'總圖', floor:3, group:'語言學習區', machine_name:'L301')
Machine.create(place:'總圖', floor:3, group:'語言學習區', machine_name:'L302')
Machine.create(place:'總圖', floor:3, group:'語言學習區', machine_name:'L303')
Machine.create(place:'總圖', floor:3, group:'語言學習區', machine_name:'L304')
Machine.create(place:'總圖', floor:3, group:'語言學習區', machine_name:'L305')
Machine.create(place:'總圖', floor:3, group:'語言學習區', machine_name:'L306')

Machine.create(place:'總圖', floor:3, group:'調閱室', machine_name:'S301')
Machine.create(place:'總圖', floor:3, group:'調閱室', machine_name:'S302')
Machine.create(place:'總圖', floor:3, group:'調閱室', machine_name:'S303')
Machine.create(place:'總圖', floor:3, group:'調閱室', machine_name:'S304')

Machine.create(place:'人社', floor:1, group:'書架區', machine_name:'HA-1F-AIO-1')
Machine.create(place:'人社', floor:1, group:'書架區', machine_name:'HA-1F-AIO-2')
Machine.create(place:'人社', floor:1, group:'書架區', machine_name:'HA-1F-AIO-3')
Machine.create(place:'人社', floor:1, group:'書架區', machine_name:'HA-1F-AIO-4')
Machine.create(place:'人社', floor:1, group:'公用電腦', machine_name:'HS-1F01')
Machine.create(place:'人社', floor:1, group:'公用電腦', machine_name:'HS-1F02')
Machine.create(place:'人社', floor:1, group:'公用電腦', machine_name:'HS-1F03')
Machine.create(place:'人社', floor:1, group:'公用電腦', machine_name:'HS-1F04')
Machine.create(place:'人社', floor:1, group:'公用電腦', machine_name:'HS-1FScanner')

Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F01')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F02')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F03')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F04')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F05')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F06')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F07')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F08')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F09')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F10')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F11')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F12')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F13')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F14')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F15')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F16')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F17')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F18')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F19')
Machine.create(place:'人社', floor:2, group:'公用電腦', machine_name:'HS-2F縮')

